name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        ex: [ex00, ex01, ex02, ex03, ex04, ex05, ex06, ex07, ex08, ex09, ex10, ex11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        uses: actions/setup-cpp@v1
        with:
          compiler: gcc
          # version: '10'  # Uncomment to specify GCC version 10 explicitly

      - name: Create logs directory
        run: mkdir -p $GITHUB_WORKSPACE/logs/$GITHUB_JOB

      - name: Build and Test
        run: |
          cd ${{ matrix.ex }}
          if [ -f Makefile ]; then
            make clean > $GITHUB_WORKSPACE/logs/$GITHUB_JOB/${{ matrix.ex }}_make_clean.log 2>&1
            make > $GITHUB_WORKSPACE/logs/$GITHUB_JOB/${{ matrix.ex }}_make.log 2>&1
            make test > $GITHUB_WORKSPACE/logs/$GITHUB_JOB/${{ matrix.ex }}_test.log 2>&1 || echo "No tests defined for ${{ matrix.ex }}"
          else
            echo "No Makefile found for ${{ matrix.ex }}" > $GITHUB_WORKSPACE/logs/$GITHUB_JOB/${{ matrix.ex }}_info.log
          fi

      - name: Display build log for debugging
        run: |
          for log_file in $GITHUB_WORKSPACE/logs/$GITHUB_JOB/*.log; do
            echo "Content of $log_file:"
            cat $log_file
          done

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.ex }}-logs
          path: $GITHUB_WORKSPACE/logs/$GITHUB_JOB/

